### ISSUE TITLE
Double backslashes don't escape properly

### ISSUE THREAD

**Issue by pratul** [MacIrssi/MacIrssi#9] opened 2010-06-16 19:28 UTC
If I want to enter the text "/msg is what you need", I can type "//msg is what you need" in irssi and it automatically escapes the slash and outputs just one. This doesn't work on MacIrssi.

**Comment by pratul** [comment] 2010-06-16 19:32
I just found out that "/ /msg is what you need" does what I want, but it still isn't what it should be, right?

**Comment by ghost** [comment] 2010-06-17 16:17
I was told that's what it should be, though I can endavour to find out. As far as I'm aware "/ /foo" produces "/foo" (with no leading space) in normal Irssi.

**Comment by ghost** [comment] 2010-06-17 17:46
Closing, not a bug.

**Closed as completed by ghost** 2010-06-17 17:46 UTC
